CREATE DATABASE WEBDEV_DB;

USE WEBDEV_DB;

CREATE TABLE USERS 
(
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  LOGIN VARCHAR(30) NOT NULL UNIQUE,
  PASSWORD VARCHAR(128) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  SECOND_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  PHONE VARCHAR(20)
);

-- test value --
INSERT
	INTO USERS (LOGIN, PASSWORD, NAME, SECOND_NAME, EMAIL, PHONE)
	VALUES ("123", "123", "123", "123", "123", "123");